name: Exception Code Check
on: pull_request

jobs:
  addedFilesList:
    runs-on: ubuntu-latest
    outputs:
      addedfiles: ${{ steps.set-added-files.outputs.addedfiles }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Get Master branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Get list of Added files
        id: set-added-files
        run: echo addedfiles=$(git diff --name-only --diff-filter=ACRT origin/${{ github.event.pull_request.base.ref }} HEAD | uniq | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)') >>$GITHUB_OUTPUT

      - name: Print files to be validated
        run: |
          if [[ -n "${{ steps.set-added-files.outputs.addedfiles }}" ]]; then
            echo "Files to be validated: ${{ steps.set-added-files.outputs.addedfiles }}"
          else
            echo "No files have been provided for validation."
          fi

  analyze_dag_files:
    runs-on: ubuntu-latest
    needs: addedFilesList
    if: ${{ needs.addedFilesList.outputs.addedfiles != '' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install tabulate

      - name: Validate top level code
        env:
          addedfiles: ${{ needs.addedFilesList.outputs.addedfiles }}
        run: |
          echo "Added files are:" $addedfiles
          ls
          pwd
      - name: Analyze Python functions
        run: |
          python exception_check.py $addedfiles
